[package]
name = "matryoshka-cli"
version = "0.0.0-git"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
matryoshka-core = { path = "../matryoshka-core" }
serde_json = "1.0"
serde_yaml = "0.9"
anyhow = "1.0"
